In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!pip install xlrd

In [3]:
df=pd.read_excel('tableau.xlsx')
df.head()

Year         Sex                 Age Race and Hispanic Origin  \
0  2014  Both Sexes         15-24 years    All Races-All Origins   
1  2012        Male         15-24 years       Non-Hispanic White   
2  2008        Male  Less than 15 years       Non-Hispanic Black   
3  2003  Both Sexes         35-44 years       Non-Hispanic White   
4  2010      Female  Less than 15 years       Non-Hispanic White   

           State  Deaths  Population  Crude Death Rate  \
0  United States    3798    43979821            8.6358   
1  United States    2137    12857283           16.6209   
2  United States      15     4687984            0.3200   
3  United States    6533    30270056           21.5824   
4  United States      28    16460571            0.1701   

   Standard Error for Crude Rate  Low Confidence Limit for Crude Rate  \
0                        0.14013                               8.3611   
1                        0.35954                              15.9162   
2                        0.08262                               0.1791   
3                        0.26702                              21.0590   
4                        0.03215                               0.1130   

   Upper Confidence Limit for Crude Rate  US Crude Rate  US Age-adjusted Rate  
0                                 8.9104        14.7574               14.6831  
1                                17.3256        13.2208               13.1422  
2                                 0.5277        11.9864               11.8947  
3                                22.1057         8.8881                8.8765  
4                                 0.2458        12.4144               12.2966

In [4]:
df1=df[df.Sex!='Both Sexes'].reset_index()

In [5]:
df=df1[df1.Age!='All Ages'].reset_index()

In [6]:
df.isnull().sum()

level_0                                  0
index                                    0
Year                                     0
Sex                                      0
Age                                      0
Race and Hispanic Origin                 0
State                                    0
Deaths                                   0
Population                               0
Crude Death Rate                         0
Standard Error for Crude Rate            0
Low Confidence Limit for Crude Rate      0
Upper Confidence Limit for Crude Rate    0
US Crude Rate                            0
US Age-adjusted Rate                     0
dtype: int64

In [7]:
df.head()

level_0  index  Year     Sex                 Age Race and Hispanic Origin  \
0        0      1  2012    Male         15-24 years       Non-Hispanic White   
1        1      2  2008    Male  Less than 15 years       Non-Hispanic Black   
2        2      4  2010  Female  Less than 15 years       Non-Hispanic White   
3        3      6  2003    Male  Less than 15 years       Non-Hispanic White   
4        4      9  2001    Male         55-64 years       Non-Hispanic Black   

           State  Deaths  Population  Crude Death Rate  \
0  United States    2137    12857283           16.6209   
1  United States      15     4687984            0.3200   
2  United States      28    16460571            0.1701   
3  United States      38    18562010            0.2047   
4  United States     129     1100021           11.7270   

   Standard Error for Crude Rate  Low Confidence Limit for Crude Rate  \
0                        0.35954                              15.9162   
1                        0.08262                               0.1791   
2                        0.03215                               0.1130   
3                        0.03321                               0.1449   
4                        1.03251                               9.7033   

   Upper Confidence Limit for Crude Rate  US Crude Rate  US Age-adjusted Rate  
0                                17.3256        13.2208               13.1422  
1                                 0.5277        11.9864               11.8947  
2                                 0.2458        12.4144               12.2966  
3                                 0.2810         8.8881                8.8765  
4                                13.7508         6.8057                6.7922

In [8]:
df.corr()

level_0     index      Year    Deaths  \
level_0                                1.000000  0.999899  0.001133  0.041070   
index                                  0.999899  1.000000  0.001484  0.040952   
Year                                   0.001133  0.001484  1.000000  0.196795   
Deaths                                 0.041070  0.040952  0.196795  1.000000   
Population                             0.026915  0.026646  0.046506  0.571823   
Crude Death Rate                       0.015528  0.015462  0.239332  0.788419   
Standard Error for Crude Rate         -0.029946 -0.029561  0.072819 -0.045788   
Low Confidence Limit for Crude Rate    0.017636  0.017546  0.240833  0.811238   
Upper Confidence Limit for Crude Rate  0.013220  0.013180  0.236277  0.763824   
US Crude Rate                         -0.003955 -0.003643  0.982853  0.198929   
US Age-adjusted Rate                  -0.004128 -0.003826  0.982002  0.198923   

                                       Population  Crude Death Rate  \
level_0                                  0.026915          0.015528   
index                                    0.026646          0.015462   
Year                                     0.046506          0.239332   
Deaths                                   0.571823          0.788419   
Population                               1.000000          0.210774   
Crude Death Rate                         0.210774          1.000000   
Standard Error for Crude Rate           -0.565553          0.450439   
Low Confidence Limit for Crude Rate      0.247885          0.998725   
Upper Confidence Limit for Crude Rate    0.168222          0.998285   
US Crude Rate                            0.045832          0.244303   
US Age-adjusted Rate                     0.045781          0.244493   

                                       Standard Error for Crude Rate  \
level_0                                                    -0.029946   
index                                                      -0.029561   
Year                                                        0.072819   
Deaths                                                     -0.045788   
Population                                                 -0.565553   
Crude Death Rate                                            0.450439   
Standard Error for Crude Rate                               1.000000   
Low Confidence Limit for Crude Rate                         0.405005   
Upper Confidence Limit for Crude Rate                       0.501092   
US Crude Rate                                               0.078387   
US Age-adjusted Rate                                        0.078586   

                                       Low Confidence Limit for Crude Rate  \
level_0                                                           0.017636   
index                                                             0.017546   
Year                                                              0.240833   
Deaths                                                            0.811238   
Population                                                        0.247885   
Crude Death Rate                                                  0.998725   
Standard Error for Crude Rate                                     0.405005   
Low Confidence Limit for Crude Rate                               1.000000   
Upper Confidence Limit for Crude Rate                             0.994169   
US Crude Rate                                                     0.245607   
US Age-adjusted Rate                                              0.245792   

                                       Upper Confidence Limit for Crude Rate  \
level_0                                                             0.013220   
index                                                               0.013180   
Year                                                                0.236277   
Deaths                                                              0.763824   
Population  

In [9]:
df.head()

level_0  index  Year     Sex                 Age Race and Hispanic Origin  \
0        0      1  2012    Male         15-24 years       Non-Hispanic White   
1        1      2  2008    Male  Less than 15 years       Non-Hispanic Black   
2        2      4  2010  Female  Less than 15 years       Non-Hispanic White   
3        3      6  2003    Male  Less than 15 years       Non-Hispanic White   
4        4      9  2001    Male         55-64 years       Non-Hispanic Black   

           State  Deaths  Population  Crude Death Rate  \
0  United States    2137    12857283           16.6209   
1  United States      15     4687984            0.3200   
2  United States      28    16460571            0.1701   
3  United States      38    18562010            0.2047   
4  United States     129     1100021           11.7270   

   Standard Error for Crude Rate  Low Confidence Limit for Crude Rate  \
0                        0.35954                              15.9162   
1                        0.08262                               0.1791   
2                        0.03215                               0.1130   
3                        0.03321                               0.1449   
4                        1.03251                               9.7033   

   Upper Confidence Limit for Crude Rate  US Crude Rate  US Age-adjusted Rate  
0                                17.3256        13.2208               13.1422  
1                                 0.5277        11.9864               11.8947  
2                                 0.2458        12.4144               12.2966  
3                                 0.2810         8.8881                8.8765  
4                                13.7508         6.8057                6.7922

In [10]:
df=df.drop(columns=['level_0','Standard Error for Crude Rate','Year','State','Race and Hispanic Origin','index'])

In [11]:
df.head()

Sex                 Age  Deaths  Population  Crude Death Rate  \
0    Male         15-24 years    2137    12857283           16.6209   
1    Male  Less than 15 years      15     4687984            0.3200   
2  Female  Less than 15 years      28    16460571            0.1701   
3    Male  Less than 15 years      38    18562010            0.2047   
4    Male         55-64 years     129     1100021           11.7270   

   Low Confidence Limit for Crude Rate  Upper Confidence Limit for Crude Rate  \
0                              15.9162                                17.3256   
1                               0.1791                                 0.5277   
2                               0.1130                                 0.2458   
3                               0.1449                                 0.2810   
4                               9.7033                                13.7508   

   US Crude Rate  US Age-adjusted Rate  
0        13.2208               13.1422  
1        11.9864               11.8947  
2        12.4144               12.2966  
3         8.8881                8.8765  
4         6.8057                6.7922

In [12]:
x=df.drop('Deaths',axis=1).values
y=df['Deaths'].values

In [13]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer

In [14]:
labelencoder=LabelEncoder()
x[:,0]=labelencoder.fit_transform(x[:,0])

In [15]:
x

array([[1, '15-24 years', 12857283, ..., 17.3256, 13.2208, 13.1422],
       [1, 'Less than 15 years', 4687984, ..., 0.5277, 11.9864, 11.8947],
       [0, 'Less than 15 years', 16460571, ..., 0.2458, 12.4144, 12.2966],
       ...,
       [1, '25-34 years', 4222625, ..., 11.3689, 11.9543, 11.8775],
       [0, 'Less than 15 years', 16976468, ..., 0.273, 11.5373, 11.4883],
       [1, '55-64 years', 803574, ..., 6.7783, 6.1882, 6.1749]],
      dtype=object)

In [16]:
columntranform=ColumnTransformer([('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=columntranform.fit_transform(x)

In [17]:
x

array([[1.0, 0.0, 0.0, ..., 17.3256, 13.2208, 13.1422],
       [0.0, 0.0, 0.0, ..., 0.5277, 11.9864, 11.8947],
       [0.0, 0.0, 0.0, ..., 0.2458, 12.4144, 12.2966],
       ...,
       [0.0, 1.0, 0.0, ..., 11.3689, 11.9543, 11.8775],
       [0.0, 0.0, 0.0, ..., 0.273, 11.5373, 11.4883],
       [0.0, 0.0, 0.0, ..., 6.7783, 6.1882, 6.1749]], dtype=object)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [19]:
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

In [20]:
forest=RandomForestRegressor(n_estimators=20)
svm=SVR(kernel='linear')

In [22]:
forest.fit(x_train,y_train)

RandomForestRegressor(n_estimators=20)

In [23]:
pred=forest.predict(x_test)

In [24]:
from sklearn.metrics import mean_squared_error

In [27]:
y_test[:10]

array([ 286,   14,  482, 2045,    4,   41,  371,    9, 2301,  176],
      dtype=int64)

In [28]:
pred[:10]

array([ 295.95,   13.9 ,  494.15, 1911.6 ,    3.85,   45.95,  368.95,
          7.85, 2308.  ,  172.7 ])

In [29]:
import math

In [32]:
math.sqrt(mean_squared_error(y_test,pred))

73.95706827104296

In [33]:
df.describe()

Deaths    Population  Crude Death Rate  \
count  1088.000000  1.088000e+03       1088.000000   
mean   1032.509191  9.127061e+06          9.585562   
std    1579.795584  7.881673e+06          9.497293   
min       1.000000  2.381630e+05          0.038900   
25%      54.000000  2.586605e+06          2.722375   
50%     294.500000  6.455414e+06          5.515500   
75%    1075.250000  1.453662e+07         14.793050   
max    8450.000000  3.128893e+07         53.498900   

       Low Confidence Limit for Crude Rate  \
count                          1088.000000   
mean                              8.820002   
std                               9.242423   
min                               0.008000   
25%                               1.865400   
50%                               4.874000   
75%                              13.734400   
max                              52.234200   

       Upper Confidence Limit for Crude Rate  US Crude Rate  \
count                            1088.000000    1088.000000   
mean                               10.427798      10.998135   
std                                 9.725878       2.946006   
min                                 0.113500       6.038200   
25%                                 3.510150       8.888100   
50%                                 6.437750      11.954300   
75%                                15.908625      13.220800   
max                                54.763600      16.304000   

       US Age-adjusted Rate  
count           1088.000000  
mean              10.949912  
std                2.915632  
min                6.057000  
25%                8.876500  
50%               11.877500  
75%               13.142200  
max               16.292300

In [34]:
svm=SVR()

In [35]:
svm.fit(x_train,y_train)

SVR()

In [36]:
pred1=svm.predict(x_test)