In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19          19000.0          0
1  15810944    Male   35          20000.0          0
2  15668575  Female   26          43000.0          0
3  15603246  Female   27          57000.0          0
4  15804002    Male   19          76000.0          0

In [4]:
df.isnull().sum()

User ID             0
Gender             23
Age                 0
EstimatedSalary    22
Purchased           0
dtype: int64

In [5]:
df.groupby('Gender').size()

Gender
Female    192
Male      185
dtype: int64

In [6]:
df['Gender']=df['Gender'].fillna('Male')

In [7]:
df['EstimatedSalary']=df['EstimatedSalary'].fillna(df['EstimatedSalary'].mean())

In [8]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [9]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19          19000.0          0
1  15810944    Male   35          20000.0          0
2  15668575  Female   26          43000.0          0
3  15603246  Female   27          57000.0          0
4  15804002    Male   19          76000.0          0

In [10]:
x=df.iloc[:,1:4].values

In [11]:
y=df.iloc[:,4].values

In [12]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder=LabelEncoder()
x[:,0]=labelencoder.fit_transform(x[:,0])
onehotencoder=OneHotEncoder(categorical_features=[0])
x=onehotencoder.fit_transform(x).toarray()

C:\Users\Arindam\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Arindam\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [14]:
pd.DataFrame(x)

0    1     2         3
0    0.0  1.0  19.0   19000.0
1    0.0  1.0  35.0   20000.0
2    1.0  0.0  26.0   43000.0
3    1.0  0.0  27.0   57000.0
4    0.0  1.0  19.0   76000.0
5    0.0  1.0  27.0   58000.0
6    1.0  0.0  27.0   84000.0
7    1.0  0.0  32.0  150000.0
8    0.0  1.0  25.0   33000.0
9    1.0  0.0  35.0   65000.0
10   1.0  0.0  26.0   80000.0
11   1.0  0.0  26.0   52000.0
12   0.0  1.0  20.0   86000.0
13   0.0  1.0  32.0   18000.0
14   0.0  1.0  18.0   82000.0
15   0.0  1.0  29.0   80000.0
16   0.0  1.0  47.0   25000.0
17   0.0  1.0  45.0   26000.0
18   0.0  1.0  46.0   28000.0
19   1.0  0.0  48.0   29000.0
20   0.0  1.0  45.0   22000.0
21   1.0  0.0  47.0   49000.0
22   0.0  1.0  48.0   41000.0
23   1.0  0.0  45.0   22000.0
24   0.0  1.0  46.0   23000.0
25   0.0  1.0  47.0   20000.0
26   0.0  1.0  49.0   28000.0
27   1.0  0.0  47.0   30000.0
28   0.0  1.0  29.0   43000.0
29   0.0  1.0  31.0   18000.0
..   ...  ...   ...       ...
370  1.0  0.0  60.0   46000.0
371  0.0  1.0  60.0   83000.0
372  1.0  0.0  39.0   73000.0
373  0.0  1.0  59.0  130000.0
374  1.0  0.0  37.0   80000.0
375  1.0  0.0  46.0   32000.0
376  1.0  0.0  46.0   74000.0
377  1.0  0.0  42.0   53000.0
378  0.0  1.0  41.0   87000.0
379  1.0  0.0  58.0   23000.0
380  0.0  1.0  42.0   64000.0
381  0.0  1.0  48.0   33000.0
382  1.0  0.0  44.0  139000.0
383  0.0  1.0  49.0   28000.0
384  1.0  0.0  57.0   33000.0
385  0.0  1.0  56.0   60000.0
386  1.0  0.0  49.0   39000.0
387  0.0  1.0  39.0   71000.0
388  0.0  1.0  47.0   34000.0
389  1.0  0.0  48.0   35000.0
390  0.0  1.0  48.0   33000.0
391  0.0  1.0  47.0   23000.0
392  1.0  0.0  45.0   45000.0
393  0.0  1.0  60.0   42000.0
394  1.0  0.0  39.0   59000.0
395  1.0  0.0  46.0   41000.0
396  0.0  1.0  51.0   23000.0
397  1.0  0.0  50.0   20000.0
398  0.0  1.0  36.0   33000.0
399  1.0  0.0  49.0   36000.0

[400 rows x 4 columns]

In [16]:
x=x[:,1:4]

In [17]:
x

array([[1.0e+00, 1.9e+01, 1.9e+04],
       [1.0e+00, 3.5e+01, 2.0e+04],
       [0.0e+00, 2.6e+01, 4.3e+04],
       ...,
       [0.0e+00, 5.0e+01, 2.0e+04],
       [1.0e+00, 3.6e+01, 3.3e+04],
       [0.0e+00, 4.9e+01, 3.6e+04]])

In [18]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_x.fit_transform(x)

array([[ 0.96076892, -1.78179743, -1.52194089],
       [ 0.96076892, -0.25358736, -1.49184602],
       [-1.040833  , -1.11320552, -0.79966386],
       ...,
       [-1.040833  ,  1.17910958, -1.49184602],
       [ 0.96076892, -0.15807423, -1.10061262],
       [-1.040833  ,  1.08359645, -1.01032799]])

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [20]:
from sklearn.linear_model import LogisticRegression
log_regression=LogisticRegression()
log_regression.fit(x_train,y_train)

C:\Users\Arindam\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
y_pred_log=log_regression.predict(x_test)

In [22]:
y_pred_log

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [23]:
from sklearn.naive_bayes import GaussianNB
naive_regressor=GaussianNB()
naive_regressor.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [24]:
y_pred_naive=naive_regressor.predict(x_test)

In [53]:
y_pred_naive

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [54]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred_naive)

array([[63,  4],
       [ 4, 29]], dtype=int64)

In [25]:
from sklearn.svm import SVC
svc_regressor_sigmoid=SVC(kernel='sigmoid')
svc_regressor_sigmoid.fit(x_train,y_train)

C:\Users\Arindam\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [55]:
confusion_matrix(y_test,y_svc_sigmoid)

array([[67,  0],
       [33,  0]], dtype=int64)

In [26]:
y_svc_sigmoid=svc_regressor_sigmoid.predict(x_test)

In [29]:
from sklearn.svm import SVC
svc_regressor_linear=SVC(kernel='linear')
svc_regressor_linear.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [30]:
y_pred_linear=svc_regressor_linear.predict(x_test)

In [31]:
y_pred_linear

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [32]:
from sklearn.svm import SVC
svc_regressor_rbf=SVC(kernel='rbf')
svc_regressor_rbf.fit(x_train,y_train)

C:\Users\Arindam\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [33]:
y_pred_rbf=svc_regressor_rbf.predict(x_test)

In [34]:
y_pred_rbf

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [40]:
from sklearn.neighbors import KNeighborsClassifier
regressor_knn=KNeighborsClassifier(n_neighbors=5,metric='euclidean',p=2)
regressor_knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [41]:
y_pred_knn=regressor_knn.predict(x_test)

In [42]:
y_pred_knn

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [46]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred_knn)


array([[58,  9],
       [10, 23]], dtype=int64)

In [47]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_knn)

0.81

In [48]:
accuracy_score(y_test,y_pred_log)

0.67

In [49]:
accuracy_score(y_test,y_pred_linear)

0.8

In [50]:
accuracy_score(y_test,y_pred_naive)

0.92

In [51]:
accuracy_score(y_test,y_pred_rbf)

0.72

In [52]:
accuracy_score(y_test,y_svc_sigmoid)

0.67